#define STATE_STARTING 10
#define STATE_IDLE 20
#define STATE_TRIGGERED 30
#define STATE_COUNTDOWN 40
#define STATE_MEETING_START 50
#define STATE_MEETING_IN_PROGRESS 60
#define STATE_MEETING_END 70

